# Generated by Django 3.1.3 on 2020-11-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pochta_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
