# Generated by Django 3.1.3 on 2020-11-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pochta_main', '0005_fileparse_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_addr', models.CharField(max_length=300, verbose_name='Исходный адрес')),
                ('source_index', models.CharField(max_length=6, verbose_name='Исходный индекс')),
                ('get_addr', models.CharField(max_length=300, verbose_name='Полученный адрес')),
                ('state', models.IntegerField(default=0, verbose_name='Статус')),
                ('not_recognize', models.CharField(max_length=5, verbose_name='Полученный адрес')),
                ('accuracy', models.CharField(max_length=3, verbose_name='Код точности')),
                ('time_answer', models.IntegerField(default=0, verbose_name='Время ответа')),
                ('field_index', models.CharField(max_length=6, verbose_name='Индекс')),
                ('field_C', models.CharField(max_length=100, verbose_name='Страна')),
                ('field_R', models.CharField(max_length=100, verbose_name='Регион')),
                ('field_A', models.CharField(max_length=100, verbose_name='Район')),
                ('field_P', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('field_T', models.CharField(max_length=100, verbose_name='Внутригородская территория')),
                ('field_S', models.CharField(max_length=100, verbose_name='Улично-дорожные элементы')),
                ('field_N', models.IntegerField(default=0, verbose_name='Номер дома')),
                ('field_NL', models.CharField(max_length=2, verbose_name='Литера')),
                ('field_D', models.CharField(max_length=2, verbose_name='Дробь')),
                ('field_E', models.IntegerField(default=0, verbose_name='Корпус')),
                ('field_B', models.IntegerField(default=0, verbose_name='Строение')),
                ('field_F', models.IntegerField(default=0, verbose_name='Помещение')),
                ('field_BOX', models.IntegerField(default=0, verbose_name='Абонентский ящик')),
                ('ident_low', models.CharField(max_length=50, verbose_name='Идентификатор нижнего уровня')),
                ('latitude', models.CharField(max_length=10, verbose_name='Широта')),
                ('longtitude', models.CharField(max_length=10, verbose_name='Долгота')),
                ('num_dest_post', models.IntegerField(default=0, verbose_name='Номер участка')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pochta_main.fileparse')),
            ],
        ),
    ]
