# Generated by Django 3.1.3 on 2020-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochta_main', '0006_fileresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_req', models.DateField(auto_now=True)),
                ('count_req', models.IntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=models.Model, to='pochta_main.fileparse')),
            ],
        ),
    ]
